### ISSUE TITLE
License & contributing

### ISSUE THREAD

**Issue by palrogg** [markhorsell/if-player-react#31]
Hello,
As a react TS developer and fan of Z-machine games, I'm very interested in your project.
Are you open to contributions? In this case, could you add a license and one or two guidelines about how you'd like to handle it?
Best

**Comment by markhorsell** [comment]
Hello, 
A license has now been added. My only real concern is keeping the current games backwards compatible. Apart from that have fun, id love to see what you do with it.
Regards
Mark
